# Site settings
author: Ruth K.
title: Coding:
header-img: img/home-bg.png
email: rutht.kebede@gmail.com
copyright_name: Ruth K.
description: > # this means to ignore newlines until "baseurl:"
  Ruth Edition
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Rkebede

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
